# Config file for demo site https://sk3.jsiu.dev
#
# This is used in combine with exampleSite/config.toml

baseURL = "https://sk3.jsiu.dev"
theme   = "sk3"
title   = "SK3"

DefaultContentLanguage = "en"
enableGitInfo          = true
enableInlineShortcodes = true
languageCode           = "en"
paginate               = 12
relativeURLs           = true

[Params]
# enableExternalSvg    = true
enableInfoBox        = true
enableListLastModify = true
enableOpenToc        = true
enableUserCanonical  = false
favicon              = "/favicon.ico"
mainSections         = "post"
pagewidth            = "1200px"
startdate            = "2012-12-02"
subtitle             = "A Hugo Theme"

# Fill in following if using Open Graph / Twitter Card
description       = "Hugo Theme SK3 Demo Site"
enableOpenGraph   = true
enableTwitterCard = true
title             = "Hugo Theme SK3 Demo Site(params)"

	[Params.paypal]
	# amount          = "5"
	businessId      = "HZF49NM9D35SJ"
	currency        = "CAD"
	enableRecurring = true

	[Params.card]
	date    = true
	summary = true
	# width = "32%"

	# [Params.color]
	# bg     = "white"
	# border = "black"
	# link   = "#3d84ff"
	# text   = "black"

	[Params.sociallink]
	facebook       = "john.siu.714"
	flickr         = "johnsiu-com"
	github         = "J-Siu"
	instagram      = "john.sd.siu"
	linkedin       = "john-sing-dao-siu"
	pinterest      = "johnsdsiu"
	reddit         = "js1943"
	rss            = true
	stack-exchange = "1882213"
	stack-overflow = "1810391"
	tumblr         = "jsds"
	twitter        = "JohnSiuCom"
	vimeo          = "user88929197"
	youtubechannel = "UC5LvdqfL2PubOp904UnUJAg"
	youtubeuser    = "JohnSDSiu"

	[Params.socialshare]
	facebook  = true
	linkedin  = true
	pinterest = true
	reddit    = true
	telegram  = true
	twitter   = true
	vk        = true

[markup]
defaultMarkdownHandler = "goldmark"

	[markup.highlight]
	codeFences         = true
	guessSyntax        = false
	hl_Lines           = ""
	lineNoStart        = 1
	lineNos            = true
	lineNumbersInTable = true
	noClasses          = true
	style              = "fruity"
	tabWidth           = 4

	[markup.tableOfContents]
	endLevel   = 6
	ordered    = false
	startLevel = 1

	[markup.goldmark]
		[markup.goldmark.extensions]
		definitionList = true
		footnote       = true
		linkify        = true
		strikethrough  = true
		table          = true
		taskList       = true
		typographer    = true
		[markup.goldmark.parser]
		attribute         = true
		autoHeadingID     = true
		autoHeadingIDType = "github"
		[markup.goldmark.renderer]
		hardWraps = false
		unsafe    = true
		xhtml     = false
